services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://localhost:3001}
    ports:
      - "3000:3000"
    
    networks:
      - app-network

networks:
  app-network:
    external: true