name: Build and Push Docker Image

on:
  release:
    types: [published]  # Trigger only when a new GitHub release is published
  workflow_dispatch:     # Allow manual trigger

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image version
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION="${GITHUB_REF#refs/tags/}"
          else
            VERSION="${GITHUB_SHA::7}"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME=ghcr.io/${REPO_LOWER}:${{ env.VERSION }}
          docker build -t $IMAGE_NAME .
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          
      - name: Push Docker image
        run: docker push ${{ env.IMAGE_NAME }}
        
      # - name: Notify Slack
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      #   run: |
      #     REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
      #     IMAGE_NAME=ghcr.io/${REPO_LOWER}:${{ env.VERSION }}
      #     MESSAGE=":tada: Backend-api build completed - Version: $VERSION - Image: \`$IMAGE_NAME\`"

      #     PAYLOAD=$(jq -n --arg text "$MESSAGE" '{text: $text}')

      #     curl -X POST -H 'Content-type: application/json' \
      #       --data "$PAYLOAD" \
      #       "$SLACK_WEBHOOK_URL"
